
TRUNCATE TABLE "cinema" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "category" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "movie" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "rating" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "hall" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "showtime" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;